### ISSUE TITLE
Add extension methods for numeric data types to simplify the usage

### ISSUE THREAD

**Issue by krcwijesinghe** [milutinovici/metric#3]
Add extension methods to numeric data types for commonly used units (these methods can have overloads to give the prefix and the power),

e.g.     
-  10.m(Prefix.k) + 5.m()  for 10 km + 5 m
  -  5.m(3)   for 5 m^3

**Comment by milutinovici** [comment]
This is a nice idea, but I'm not sure which are commonly used units. And this could potentially be a huge amount of methods. It would be 2 of them per numeric type per unit type. 

```csharp
pulic static Unit m(this double number, double power = 1);
pulic static Unit m(this double number, Prefix prefix, double power=1);
pulic static Unit m(this int number, double power = 1);
pulic static Unit m(this int number, Prefix prefix, double power=1);
pulic static Unit m(this float number, double power = 1);
pulic static Unit m(this float number, Prefix prefix, double power=1);
....
```
Since there are 11 numeric types in c# that would be 22 methods per "common" unit. If by common, you mean base units, there would be 7*22(154) methods to implement. If we include derived units, that number goes to 22*22(484 methods!)

Although the api would be nicer. 

Tell me which units do you think are common?

**Comment by milutinovici** [comment]
After giving it some thought, I concluded that extending only int and double is enough. And I could add extension methods for all standard units. The methods would be in a separate namespace, so using them would be opt in.

How do you feel about this solution?

**Comment by krcwijesinghe** [comment]
Yes, that is good.

Thanks.
